//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITJobs.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Job = new HashSet<Job>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string LogoPath { get; set; }
        public string Url { get; set; }
        public string ContactEmail { get; set; }
    
        public virtual ICollection<Job> Job { get; set; }
    }
}
